// Generated by wrangler types
interface Env {
	ENVIRONMENT: "development";
	AI_GATEWAY_NAME: "duplex-extraction";
	R2_BUCKET_NAME: "duplex-conversations";
	WORKOS_CLIENT_ID: string;
	CF_ACCOUNT_ID: string;
	ANTHROPIC_API_KEY: string;
	CF_AIG_TOKEN: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	CONVERSATIONS_BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
	EXTRACT_WORKFLOW: Workflow;
}
